### ISSUE TITLE
Error: Unable to compose texture because there is no game canvas

### ISSUE THREAD

**Issue by ravingdragoon** [ironmonk88/monks-little-details#129] opened 2021-12-22 14:53 UTC
When running the latest version in V9 "Stable" I get the following error before the canvas renders. I will troubleshoot further, but so far I have not been able to find a cause.

```
Error: Unable to compose texture because there is no game canvas
[Detected 1 package: monks-little-details]
    at Function.compositeCanvasTexture (foundry.js:383)
    at Function.createThumbnail (foundry.js:360)
    at async VideoHelper.createThumbnail (foundry.js:2657)
    at async MonksCombatTracker.getData (foundry.js:58143)
    at async MonksCombatTracker.getData (combattracker.js:16)
    at async MonksCombatTracker._render (foundry.js:3031)
    at async MonksCombatTracker._render 
onError	@	foundry.js:316
🎁call_wrapped	@	libWrapper-wrapper.js:502
🎁Hooks.onError#lib-wrapper	@	listeners.js:137
🎁Hooks.onError#0	@	libWrapper-wrapper.js:182
(anonymous)	@	foundry.js:46464
Promise.catch (async)		
_render	@	foundry.js:46463
await in _render (async)		
render	@	foundry.js:2990
initializeUI	@	foundry.js:5587
setupGame	@	foundry.js:5480
await in setupGame (async)		
_initializeGameView	@	foundry.js:6434
_initializeView	@	foundry.js:6410
initialize	@	foundry.js:5380
await in initialize (async)		
🎁call_wrapped	@	libWrapper-wrapper.js:502
🎁libWrapperInit	@	libWrapper-api.js:778
await in 🎁libWrapperInit (async)		
🎁Game.prototype.initialize#0	@	libWrapper-wrapper.js:182
window.addEventListener.once	@	foundry.js:62192
```

**Comment by ravingdragoon** [comment] 2021-12-22 15:04
I got it down to just a few modules and still don't see the cause of the error. Here is the debug report:

```
Versions:
  Foundry: 9.238
  System: dnd5e version 1.5.6
User:
  Role: GAMEMASTER
Settings:
  Disable_Canvas: Disabled
  Max_FPS: 60
  Token_Drag_Vision: Disabled
  Performance_Mode: 2
  Token_Vision_Animation: Enabled
  Light_Source_Animation: Enabled
  Zoomed_Texture_Antialiasing: Enabled
  Animate_Roll_Tables: Disabled
Scene:
  Walls: 709
  Lights: 2
  Tokens: 19
  Tiles: 42
  Sounds: 11
  Drawings: 22
  Notes: 11
  Dimensions: 4800 x 6600
  Background: 4970 x 6790
  Foreground: 1190 x 975
WebGL:
  Context: WebGL2RenderingContext
  GL_Vendor: WebKit
  Renderer: WebKit WebGL
  Unmasked_Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9709)
  WebGL_Version: WebGL 2.0 (OpenGL ES 3.0 Chromium)
  MAX_TEXTURE_SIZE: 16384
  MAX_RENDERBUFFER: 16384
Database:
  Actors: 77
  Items: 173
  Scenes: 3
  Journals: 793
  Tables: 82
  Chat: 232
  Macros: 393
Data_Sizes:
  Actors: 9.9 MB
  Items: 771.75 KB
  Scenes: 697.4 KB (2 Base64 Detected)
  Journals: 5.76 MB
  Tables: 1.41 MB
  Chat: 342.68 KB (2 Base64 Detected)
  Macros: 853.89 KB
Browser:
  Platform: Win32
  Vendor: Google Inc.
  Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
Memory:
  Heap_Limit: 4 GB
  Heap_Total: 179.9 MB
  Heap_Used: 145.77 MB
Modules:
  Total: 391
  Enabled: 7
Active_Modules:
  _chatcommands: Library: Chat Commands v1.4.0
  debug-report: Debug Report Generator v0.0.5
  find-the-culprit: Find the culprit v1.4.0
  lib-wrapper: libWrapper v1.11.0.1
  monks-little-details: Monk's Little Details v1.0.41
  socketlib: socketlib v1.0.9
  forge-vtt: The Forge v1.10
```

**Comment by ironmonk88** [comment] 2022-03-18 21:38
I believe this was a foundry issue that has since been fixed.
When trying to convert an animated image to a thumbnail the foundry function failed.
I've since checked it and they added an await to make sure the canvas has been loaded.

I'm going to close it, but feel free to open it again if this wasn't the cause of the issue.

**Closed by ironmonk88** 2022-03-18 21:38 UTC
