### ISSUE TITLE
Clear Targets Not Working

### ISSUE THREAD

**Issue by Puddinglord** [ironmonk88/monks-little-details#80] opened 2021-07-10 06:58 UTC
When I the GM target a token and then advance the turn it clears my target but it doesn't clear any targets any players make. Is this the correct behavior or is this an issue?

**Comment by ironmonk88** [comment] 2021-07-10 07:40
This is the way it was designed.
Mostly because players have the time to select a target to attack, and they'll stick with it until the target is defeated.
As a GM, you're constantly changing targets as you manage multiple characters.

That being said, it could be added for the players pretty easily.

**Comment by Puddinglord** [comment] 2021-07-10 21:38
The design decision and intent are solid. Could a checkbox be added to enable clearing players' targets? Best of both worlds.

**Comment by ironmonk88** [comment] 2021-07-21 06:42
I've switched it so that the setting is available to players.
For the GM it will default to true, and for the players it will default to false.
I think that should be good.  It will maintain the same behavior as it does now, until a player specifically sets it to clear.

**Comment by Puddinglord** [comment] 2021-07-21 09:35
Love it! Thanks 🙏

**Comment by ironmonk88** [comment] 2021-08-22 19:41
Closing this as it's should have been fixed in a previous release.  :-)

**Closed by ironmonk88** 2021-08-22 19:41 UTC
Labels: fixed waiting for release
