### ISSUE TITLE
Monk's Little Details, Sort Statuses by Columns incorrect sort order

### ISSUE THREAD

**Issue by GigawattWarlock** [ironmonk88/monks-little-details#181] opened 2022-06-19 08:10 UTC
When I use Monk's Little Details in combination with DFred's Convenient Effects, I prefer to use the "Sort Statuses by Columns" option within the Little Details module settings.

Unfortunately, the list isn't alphabetized correctly if you add anything to the list.

It is possible that to reproduce this issue you may have to follow this procedure:
1. Enable DFred's Convenient Effects and Monk's Little Details.
2. Set Monk's Little Details --> Sort Status Effects --> COLUMNS (save and reload)
3. Using DFred's Convenient Effects, right-click on any effect and choose "Toggle Status Effect" (reload)

When the sorting arrangement is set to Columns, adding anything to the list causes several items to come out of order.  

<img width="379" alt="image" src="https://user-images.githubusercontent.com/98629268/174471859-944f561c-335e-4cf6-acfa-2c8c1398562b.png">

**Comment by Shareenx** [comment] 2022-06-21 19:01
Same thing happens with CUB (Combat Utility Belt)

**Comment by Shareenx** [comment] 2022-06-23 04:47
5e =)
By the way, love your modules and videos

**Comment by ronin-seven** [comment] 2022-06-24 15:45
I can reproduce this without applying any effect (#3 above).

Modules active: DFreds Convenient Effects, Monk's Little Details, libWrapper and socketlib
System: DnD5e

Default settings with the exception of:
1. DCE -> Modify Status Effects = Replace
2. MLD -> Sort Statuses = Columns

![image](https://user-images.githubusercontent.com/47235915/175570373-b25956fe-4595-4551-b35c-c81ac6110f89.png)

**Comment by ronin-seven** [comment] 2022-07-23 16:40
Looks like this is no longer an issue with the latest versions of DCE (2.7.0) and MLD (1.0.55)

**Comment by ironmonk88** [comment] 2022-09-22 05:34
This should be fixed in the latest release

**Closed by ironmonk88** 2022-09-22 05:34 UTC
Labels: fixed waiting for release
