### ISSUE TITLE
[Bug 1.0.14] Turn marker issues at end of initiative

### ISSUE THREAD

**Issue by MelvinMcSnatch** [ironmonk88/monks-little-details#21] opened 2021-03-01 03:13 UTC
Using the newest Little Details 1.0.14, the turn marker is not switching to the last token at all.  I disabled Token Mold as it was a likely culprit for incompatibility as I first thought it was a problem with NPCs pulled from the same actor entry, but no fix. I'll give a couple of examples of what's going on.

1. PC1, PC2, and Skeleton1 and Skeleton2 are added combat state and roll to the initiative tracker. PC1 goes first and is marked with the turn marker. Skeleton1 goes next, and is marked. PC2 follows and is marked. Skeleton2 goes last, but the turn marker remains on PC2. At the top of the round, the turn marker goes back to PC1.
2. Adding a Minotaur in at the end of initiative; PC1, Skeleton1, PC2, and Skeleton2 all work correctly, but the turn marker remains on Skeleton2 until the beginning of PC1's turn. 
3. PC2 is moved to the end of initiative. The turn marker remains on Minotaur, skipping PC2 on its turn, and going back to normal at the beginning of the next round with PC1.

I think I've ruled out this is a linked/unlinked/multiple token issue, and it's just not working for the last token in the initiative.

**Comment by ironmonk88** [comment] 2021-03-01 05:38
That's really weird.  It's affecting PF2E but not DnD5e.  Found what the issue is.  Should be fixed in the next release.
Thank you for finding that issue!

**Comment by MelvinMcSnatch** [comment] 2021-03-01 07:04
> That's really weird. It's affecting PF2E but not DnD5e. Found what the issue is. Should be fixed in the next release.
> Thank you for finding that issue!

Just to clarify, I'm getting this with DnD5e 0.7.9. 

I tried using it in an existing world with a different mod setup, and it worked. So I tried turning on all the mods I remembered using in the other one and it still worked. So I copied the broken games' settings file and it was broken again. I disabled all mods except Little Details but it was still broke. Then I started a brand new, sparkling clean world with only Little Details and it was broken. So it's a little inconsistent, but doesn't seem to be a conflict with any other modules.

**Comment by ironmonk88** [comment] 2021-03-01 07:21
Yeah I just had a friend check it on PF2E and it was fine.  So it's very inconsistent.
And... knowing the issue... it shouldn't have worked on any system.  So the weirdness isn't that it failed... but that somehow it was working.

**Comment by ironmonk88** [comment] 2021-03-04 06:48
1.0.15 just released with the fix.  Let me know if this is still an issue.

**Comment by MelvinMcSnatch** [comment] 2021-03-05 03:38
Looks good! Thanks!

**Closed** 2021-03-09 23:29 UTC
