### ISSUE TITLE
[BUG] Can 't wrap TokenHUD.prototype.refreshStatusIcons

### ISSUE THREAD

**Issue by alexdiste** [ironmonk88/monks-little-details#297] opened 2024-06-01 06:25 UTC
**Describe the bug**
![image](https://github.com/ironmonk88/monks-little-details/assets/82694721/c21324b2-ef19-4f0f-8587-50effe77c927)

**To Reproduce**
Open my world in a my custom system (so maybe the problem is on my side)

**Please complete as much of the following information as possible:**
 - Browser EDGE
 - Foundry Version v12 SELF HOST
 - System fvtt-warhero (https://github.com/alexdiste/fvtt-warhero)
 - Module version 12.01

**Comment by grimsdalee** [comment] 2024-06-01 15:17
This happens for me also.
I have found it is being caused by the config setting: 

![image](https://github.com/ironmonk88/monks-little-details/assets/154701625/535cde31-3525-42c2-a42c-d16b4dc6037f)

When enabled, it generates the error below + the error listed above in the OP:

![image](https://github.com/ironmonk88/monks-little-details/assets/154701625/26a1fff3-ba27-47ac-8a06-e4e857a709f2)

**Comment by ironmonk88** [comment] 2024-06-01 17:04
Duplicate of #295

**Closed by ironmonk88** 2024-06-01 17:04 UTC
Labels: duplicate
